tech_skills = [
    "Python programming",
    "JavaScript",
    "HTML/CSS",
    "React.js",
    "Node.js",
    "AngularJS",
    "Vue.js",
    "Django",
    "Flask",
    "Ruby on Rails",
    "Java",
    "C#",
    "C++",
    "Swift",
    "Kotlin",
    "Git",
    "SQL",
    "NoSQL databases",
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "GraphQL",
    "RESTful APIs",
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "Docker",
    "Kubernetes",
    "Jenkins",
    "Continuous Integration/Continuous Deployment (CI/CD)",
    "Linux system administration",
    "Bash scripting",
    "DevOps",
    "Machine learning",
    "Deep learning",
    "Data science",
    "Natural Language Processing (NLP)",
    "Computer vision",
    "Big data technologies (Hadoop, Spark)",
    "Blockchain",
    "Cryptocurrency",
    "Web development",
    "Mobile app development",
    "UI/UX design",
    "Agile methodologies",
    "Scrum",
    "Kanban",
    "Test-driven development (TDD)",
    "Microservices architecture"
]


non_tech_skills = [
    "Communication skills",
    "Teamwork",
    "Problem-solving",
    "Critical thinking",
    "Creativity",
    "Adaptability",
    "Time management",
    "Organization",
    "Leadership",
    "Emotional intelligence",
    "Active listening",
    "Conflict resolution",
    "Negotiation",
    "Decision-making",
    "Stress management",
    "Public speaking",
    "Presentation skills",
    "Networking",
    "Collaboration",
    "Empathy",
    "Resilience",
    "Attention to detail",
    "Customer service",
    "Interpersonal skills",
    "Project management",
    "Strategic planning",
    "Analytical skills",
    "Flexibility",
    "Persuasion",
    "Innovation",
    "Adaptability",
    "Cultural awareness",
    "Global mindset",
    "Financial literacy",
    "Risk management",
    "Sales skills",
    "Marketing",
    "Writing skills",
    "Research skills",
    "Time management",
    "Event planning",
    "Presentation skills",
    "Conflict resolution",
    "Assertiveness",
    "Empathy",
    "Resilience",
    "Networking",
    "Decision-making",
    "Customer service"
]
